language: php

matrix:
  fast_finish: true
  include:
    - php: 7.4
    - php: 8.0
    - php: 8.1

before_script: 
  - composer require phpunit/phpunit

script:
    - ./vendor/bin/phpunit --coverage-clover coverage.xml

after_success:
    - bash <(curl -s https://codecov.io/bash)
