language: php

matrix:
  fast_finish: true
  include:
    - php: 7.2
    - php: 7.3
    - php: 7.4
    - php: 8.0
    - php: 8.1

before_install:
  - composer self-update
  - composer install --no-interaction --dev

script:
  - composer test -- --coverage-clover=coverage.xml

after_success:
  - bash <(curl -s https://codecov.io/bash)
