language: php

env:
  global:
    - CODECOV_TOKEN=b43efda0-6b9a-42d7-b231-7a5d9219b0da

matrix:
  fast_finish: true
  include:
    - php: 7.4
    - php: 8.0

before_install:
  - composer self-update
  - composer install --prefer-source --no-interaction --dev

script:
  - php -d xdebug.mode=coverage vendor/bin/phpunit --coverage-clover coverage.xml

after_success:
  - bash <(curl -s https://codecov.io/bash)
